git clone git://github.com/Shougo/neobundle.vim
git clone git://github.com/mattn/mahjong-vim
git clone git://github.com/mattn/invader-vim
git clone git://github.com/mattn/hahhah-vim
git clone git://github.com/tpope/vim-fugitive
git clone git://github.com/Shougo/unite.vim
git clone git://github.com/Shougo/vimfiler
git clone git://github.com/tsukkee/unite-tag
git clone git://github.com/tsukkee/unite-help
git clone git://github.com/h1mesuke/unite-outline
git clone git://github.com/tacroe/unite-mark
git clone git://github.com/thinca/vim-unite-history
git clone git://github.com/Shougo/vimproc
git clone git://github.com/Shougo/vimshell
git clone git://github.com/thinca/vim-quickrun
git clone git://github.com/dannyob/quickfixstatus
git clone git://github.com/thinca/vim-ref
git clone git://github.com/thinca/vim-visualstar
git clone git://github.com/thinca/vim-poslist
git clone git://github.com/tyru/caw.vim
git clone git://github.com/sergeche/zen-coding
git clone git://github.com/thinca/vim-fontzoom
git clone git://github.com/mattn/salaryman-complete-vim
git clone git://github.com/scrooloose/syntastic
git clone git://github.com/godlygeek/tabular
git clone git://github.com/kana/vim-smartchr
git clone git://github.com/vim-ruby/vim-ruby
git clone git://github.com/msanders/cocoa.vim
git clone git://github.com/mfumi/snake.vim
git clone git://github.com/fuenor/vim-statusline
git clone git://github.com/h1mesuke/ref-dicts-en
git clone git://github.com/Takazudo/outline.vim.git
git clone git://github.com/motemen/git-vim.git
git clone git://github.com/mattn/unite-mcdonalds-vim
git clone git://github.com/mattn/unite-advent_calendar
git clone git://github.com/mattn/webapi-vim
git clone git://github.com/thinca/vim-editvar
git clone git://github.com/kien/tabman.vim
git clone git://github.com/jayed/pyclewn
git clone git://github.com/tomtom/ttoc_vim.git
git clone git://github.com/tomtom/tlib_vim.git
git clone git://github.com/mattn/zencoding-vim
git clone git://github.com/jceb/vim-hier
git clone git://github.com/scrooloose/nerdtree
git clone git://github.com/basyura/twibill.vim
git clone git://github.com/basyura/bitly.vim
git clone git://github.com/basyura/TweetVim
git clone git://github.com/osyo-manga/unite-life-game
git clone git://github.com/jcf/vim-latex
git clone git://github.com/mattn/calendar-vim
