  (setq newsticker-url-list
        '(("Slashdot" "http://rss.slashdot.org/Slashdot/slashdot")
          ("TechCrunch" "http://feeds.feedburner.com/TechCrunch")
          ("CNET Japan" "http://japan.cnet.com/rss/index.rdf")
          ("#RyoAnnaBlog" "http://d.hatena.ne.jp/RyoAnna/rss")
          ("*begejstring for DANMARK*" "http://blog.goo.ne.jp/spanske_stol/rss2.xml")
          ("75BASE" "http://luviphone.info/feed")
          ("CodeZine" "http://rss.rssad.jp/rss/codezine/new/20/index.xml")
          ("Emacsタグが付けられた新着投稿 - Qiita" "http://qiita.com/tags/Emacs/feed.atom")
          ("Engadget" "http://www.engadget.com/rss.xml")
          ("Engadget Japanese" "http://feeds.feedburner.com/engadget/japanese")
          ("Geekなぺーじ" "http://www.geekpage.jp/rss.php")
          ("GIGAZINE" "http://gigazine.net/index.php?/news/rss_2.0/")
          ("No Second Life" "http://www.ttcbn.net/no_second_life/feed")
          ("nori510.com" "http://nori510.com/feed")
          ("OZPAの表4" "http://ozpa-h4.com/?feed=atom")
          ("(rubikitch loves (Emacs Ruby CUI Books))" "http://d.hatena.ne.jp/rubikitch/rss")
          ("TuiTui" "http://tuitui.jp/atom.xml")
          ("あなたのスイッチを押すブログ" "http://kazoo1837.blog23.fc2.com/?xml")
          ("おまえは今までスキャンした本の冊数をおぼえているのか？" "http://ushigyu.net/feed/")
          ("はてなブックマーク - タグ - emacs" "http://b.hatena.ne.jp/t/emacs?sort=hot&amp;threshold=10&amp;mode=rss")
          ("はてなブックマーク - タグ - evernote" "http://b.hatena.ne.jp/t/evernote?sort=hot&amp;threshold=10&amp;mode=rss")
          ("ひよこガジェンヌ" "http://www.hiyoko-g.com/index.rdf")
          ("ぼちぼち散歩" "http://relaxedcolumn.blog8.fc2.com/?xml")
          ("ガジェット通信" "http://getnews.jp/feed")
          ("デジタルマガジン" "http://feeds.feedburner.com/digimaga")
          ("ライフハッカー［日本版］" "http://www.lifehacker.jp/index.xml")
          ("ライフハックちゃんねる弐式" "http://feeds.feedburner.com/lifehack2ch")
          ("二十歳街道まっしぐら" "http://20kaido.com/index.rdf")
          ("人工知能に関する断想録" "http://d.hatena.ne.jp/aidiary/rss")
          ("気になる、記になる…" "http://feeds.feedburner.com/taisy0")
          ("理系の人々" "http://pipes.yahoo.com/pipes/pipe.run?_id=d0e2c6435bad04292ef83e9aa12f0d2f&amp;_render=rss")
          ("2chコピペ保存道場" "http://2chcopipe.com/index.rdf")
          ("MAKE: Japan" "http://jp.makezine.com/blog/index.xml")
          ("MOON CHRONICLE" "http://miruto.org/atom.xml")
          ("Webクリエイターボックス" "http://feeds.feedburner.com/webcreatorbox/BmBY")
          ("WIRED.jp 世界最強の「テクノ」ジャーナリズム" "http://wired.jp/feed/")
          ("きなこ激安中" "http://blog.kinako.org/?mode=rss")
          ("だらだら毎日" "http://daradaramainichi.com/feed")
          ("となりの８０１ちゃん" "http://indigosong.net/atom.xml")
          ("どうでもいいこと" "http://feeds.feedburner.jp/nozeki")
          ("なんでも評点" "http://rate.livedoor.biz/index.rdf")
          ("はてなブックマーク - 人気エントリー" "http://feeds.feedburner.com/hatena/b/hotentry")
          ("らばQ" "http://feeds.feedburner.com/labaq/Mmqd")
          ("アキバBlog（秋葉原ブログ）" "http://blog.livedoor.jp/geek/index.rdf")
          ("アシタノレシピ　-明日を楽しくするレシピ集-" "http://feeds.feedburner.com/ashi-tano")
          ("カラパイア" "http://karapaia.livedoor.biz/index.rdf")
          ("スラッシュドット・ジャパン" "http://slashdot.jp/slashdotjp.rss")
          ("タネタン - あらゆる元ネタ・由来を集めるサイト -" "http://moto-neta.com/feed/")
          ("バイクと！" "http://baikuto.doorblog.jp/index.rdf")
          ("ロケットニュース24（β）" "http://feeds.rocketnews24.com/rocketnews24")
          ("初音ミクニュース" "http://hatsunemiku.blog107.fc2.com/?xml")
          ("地獄のミサワの「女に惚れさす名言集」" "http://jigokuno.com/?mode=rss")
          ("ブランドファッション通信" "http://feeds.feedburner.com/http/brandbanzaiseesaanet")
          ("マジメな男のマジメ服" "http://blackwatch.seesaa.net/index20.rdf")
          ("TechCrunch » Gaming" "http://feeds.feedburner.com/TechCrunch/Gaming")
          ("にんしんゲーム天国" "http://rssblog.ameba.jp/nin-shin/rss20.xml")
          ("ゲームは一日○時間" "http://rssblog.ameba.jp/oosakaking/rss20.xml")
          ("チラシの裏でゲーム鈍報" "http://blog.livedoor.jp/maxell011/index.rdf")
          ("Applie最新記事" "http://applie.net/applie_info.rss")
          ("apptoi" "http://feeds.feedburner.com/apptoiphone/VJZQ")
          ("iPhone 研究室（iPadもね）" "http://feeds.feedburner.com/IphoneAerialNekton")
          ("Mac Explorer" "http://idita.blog11.fc2.com/?xml")
          ("Macの手書き説明書" "http://veadardiary.blog29.fc2.com/?xml")
          ("OS X Daily" "http://feeds.feedburner.com/osxdaily")
          ("Touch Lab - タッチ ラボ" "http://feeds.feedburner.com/ipod_touch_lab")
          ("はてなブックマーク - タグ - mac" "http://b.hatena.ne.jp/t/mac?sort=hot&amp;threshold=10&amp;mode=rss")
          ("アップル - ホットニュース" "http://images.apple.com/jp/main/rss/hotnews/hotnews.rss")
          ("男子ハック" "http://feeds.feedburner.com/danshihack/NCnQ")
          ("J-CASTニュース" "http://www.j-cast.com/index.xml")
          ("JWSJ Japan Section Summaries" "http://jp.wsj.com/rss/feed/jwsj_Japan_summaries")
          ("Reuters: テクノロジー" "http://feeds.reuters.com/reuters/JPTechnologyNews")
          ("Reuters: 世界のこぼれ話" "http://feeds.reuters.com/reuters/JPOddlyEnoughNews")
          ("Top Stories - Google News" "http://fullrss.net/a/http/news.google.com/news?hl=ja&amp;ned=us&amp;ie=UTF-8&amp;oe=UTF-8&amp;output=atom&amp;topic=h")
          ("はてなブックマーク - 人気エントリー - 政治・経済" "http://b.hatena.ne.jp/hotentry/economics.rss")
          ("はてなブックマーク - 人気エントリー - 社会" "http://b.hatena.ne.jp/hotentry/social.rss")
          ("新聞社説一覧" "http://www.geocities.jp/ktaro38/rss.xml")
          ("朱鷺の杜(IBIS)ブログ" "http://ibisforest.blog4.fc2.com/?xml")
          ("電子情報通信学会 和文論文誌 D" "http://search.ieice.org/ieicejd.xml")
          ("カテゴリ合算の総合ランキング(毎時)‐ニコニコ動画" "http://www.nicovideo.jp/ranking/fav/hourly/all?rss=2.0")
          ("ゲームの総合ランキング(デイリー)‐ニコニコ動画" "http://www.nicovideo.jp/ranking/fav/daily/game?rss=2.0")
          ("マイリスト ゆっくりできない人狼‐ニコニコ動画" "http://www.nicovideo.jp/mylist/33885285?rss=2.0&amp;lang=ja-jp")
          ("マイリスト ゆっくり達のクトゥルフの呼び声‐ニコニコ動画" "http://www.nicovideo.jp/mylist/24704128?rss=2.0")
          ("マイリスト プレシデンテ春香のトロピコ建国日記‐ニコニコ動画" "http://www.nicovideo.jp/mylist/15267156?rss=2.0&amp;lang=ja-jp")
          ("BuzzFeed(big on twittew)" "http://www.buzzfeed.com/badge/big-on-twitter.xml")
          ("VOA News:  Special English" "http://www.voanews.com/templates/Articles.rss?sectionPath=/learningenglish/home")
          ("Web Designer Wall - Design Trends and Tutorials" "http://feeds.feedburner.com/WebDesignerWall")
          ("わかる！英語教材ラボ" "http://www.wakarueng.com/feed/")
          ("Big Sky" "http://mattn.kaoriya.net/index.rss")
          ("vim-jp" "http://vim-jp.org/rss.xml")
          ("Vim-users.jp" "http://vim-users.jp/feed/")
          ("Vimタグが付けられた新着投稿 - Qiita" "http://qiita.com/tags/Vim/feed.atom")
          ("はてなブックマーク - タグ - vim" "http://b.hatena.ne.jp/t/vim?sort=hot&amp;threshold=5&amp;mode=rss")
          ("名無しのvim使い" "http://nanasi.jp/rss10.rdf")
          ("永遠に未完成" "http://d.hatena.ne.jp/thinca/rss")
          ))
